apiVersion: v1
kind: Pod
metadata:
  name: container-demo-echo-pod
spec:
  containers:
  - name: container-demo-container
    image: dmaumenee/container-demo:1.0
    env:
    - name: MESSAGE
      value: "Hello World"
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(MESSAGE) at $(date); sleep 10;done"]
