apiVersion: v1
kind: Pod
metadata:
  name: container-demo-env-pod
spec:
  containers:
  - name: env-container
    image: dmaumenee/container-demo:1.0
    command: ["printenv"]
  restartPolicy: OnFailure
