apiVersion: v1
kind: Pod
metadata:
  name: container-demo-wget-pod
spec:
  containers:
  - name: wget-container
    image: dmaumenee/container-demo:1.0
    env:
    - name: URL
      value: "http://localhost:8080/ping"
    command: ["/bin/sh"]
    args: ["-c", "while true; do wget -qO- $(URL) ; sleep 10;done"]
