apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: container-demo
spec:
  selector:
    matchLabels:
      app: container-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: container-demo
    spec:
      containers:
      - name: container-demo
        image: dmaumenee/container-demo:1.0
        env:
          - name: TITLE
            value: "Formation Kubernetes"
          - name: SHOW_VERSION
            value: "true"
          - name: METADATA
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace