apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: my-namespace-rq
spec:
  limits:
  - default:
      cpu: 0.5
      memory: "256Mi"
    defaultRequest:
      cpu: 0.2
      memory: "128Mi"
    type: Container
