apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: container1
    image: busybox
    args: ["sleep", "36000"]
    resources:  #Si absent: error from server (Forbidden) car ResourceQuota present
     limits:
      memory: "200Mi"
      cpu: "1"
     requests: 
      memory: "100Mi"
      cpu: "0.5"
