apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: container-demo
  name: container-demo-svc # correspond a l'alias DNS du service
spec: 
  type: ClusterIP
  ports: 
    - port: 80
      targetPort: 8080
  selector: 
    app: container-demo