apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: container-demo
  name: container-demo-svc
spec: 
  type: LoadBalancer
  ports: 
    - port: 80
      targetPort: 8080
  selector: 
    app: container-demo