apiVersion: v1
kind: Pod
metadata:
  name: wget-pod
spec:
  containers:
  - name: wget-container
    image: alpine
    env:
    - name: URL
      value: "http://container-demo-svc/ping"
    command: ["/bin/sh"]
    args: ["-c", "while true; do wget -qO- $(URL) --timeout=5; sleep 5;done"]